export const LOGINPLAYER_SUCCESS = 'LOGINPLAYER_SUCCESS';
export const LOGINPLAYER_ERROR  = 'LOGINPLAYER_ERROR';
export const LOGINPLAYER_PENDING = 'LOGINPLAYER_PENDING';
export const LOGINPLAYER = 'LOGINPLAYER';