export const PLAYERINFORMATION_SUCCESS = 'PLAYERINFORMATION_SUCCESS';
export const PLAYERINFORMATION_ERROR  = 'PLAYERINFORMATION_ERROR';
export const PLAYERINFORMATION_PENDING = 'PLAYERINFORMATION_PENDING';
export const PLAYERINFORMATION = 'PLAYERINFORMATION';