export const ADD_PLAYER_SUCCESS = 'ADD_PLAYER_SUCCESS';
export const ADD_PLAYER_ERROR  = 'ADD_PLAYER_ERROR';
export const ADD_PLAYER_PENDING = 'ADD_PLAYER_PENDING';
export const ADD_PLAYER = 'ADD_PLAYER';

export const DELETE_PLAYER_SUCCESS = 'DELETE_PLAYER_SUCCESS';
export const DELETE_PLAYER_ERROR  = 'DELETE_PLAYER_ERROR';
export const DELETE_PLAYER_PENDING = 'DELETE_PLAYER_PENDING';
export const DELETE_PLAYER = 'DELETE_PLAYER';

export const UPDATE_PLAYER_NAME_SUCCESS = 'UPDATE_PLAYER_NAME_SUCCESS';
export const UPDATE_PLAYER_NAME_ERROR  = 'UPDATE_PLAYER_NAME_ERROR';
export const UPDATE_PLAYER_NAME_PENDING = 'UPDATE_PLAYER_NAME_PENDING';
export const UPDATE_PLAYER_NAME = 'UPDATE_PLAYER_NAME';

export const UPDATE_PLAYER_UPI_SUCCESS = 'UPDATE_PLAYER_UPI_SUCCESS';
export const UPDATE_PLAYER_UPI_ERROR  = 'UPDATE_PLAYER_UPI_ERROR';
export const UPDATE_PLAYER_UPI_PENDING = 'UPDATE_PLAYER_UPI_PENDING';
export const UPDATE_PLAYER_UPI = 'UPDATE_PLAYER_UPI';