export const MANAGEPLAYER_INFORMATION_SUCCESS = 'MANAGEPLAYER_INFORMATION_SUCCESS';
export const MANAGEPLAYER_INFORMATION_ERROR  = 'MANAGEPLAYER_INFORMATION_ERROR';
export const MANAGEPLAYER_INFORMATION_PENDING = 'MANAGEPLAYER_INFORMATION_PENDING';
export const MANAGEPLAYER_INFORMATION = 'MANAGEPLAYER_INFORMATION';