export const MANAGEPLAYER_INFORMATION_SUCCESS = 'MANAGEPLAYER_INFORMATION_SUCCESS';
export const MANAGEPLAYER_INFORMATION_ERROR  = 'MANAGEPLAYER_INFORMATION_ERROR';
export const MANAGEPLAYER_INFORMATION_PENDING = 'MANAGEPLAYER_INFORMATION_PENDING';
export const MANAGEPLAYER_INFORMATION = 'MANAGEPLAYER_INFORMATION';

export const MANAGETRANSACTIONPLAYER_INFORMATION_SUCCESS  = 'MANAGETRANSACTIONPLAYER_INFORMATION_SUCCESS ';
export const MANAGETRANSACTIONPLAYER_INFORMATION_ERROR  = 'MANAGETRANSACTIONPLAYER_INFORMATION_ERROR';
export const MANAGETRANSACTIONPLAYER_INFORMATION_PENDING = 'MANAGETRANSACTIONPLAYER_INFORMATION_PENDING';
export const MANAGETRANSACTIONPLAYER_INFORMATION = 'MANAGETRANSACTIONPLAYER_INFORMATION';