export const LOGINPLAYER_VERIFICATION_SUCCESS = 'LOGINPLAYER_VERIFICATION_SUCCESS';
export const LOGINPLAYER_VERIFICATION_ERROR  = 'LOGINPLAYER_VERIFICATION_ERROR';
export const LOGINPLAYER_VERIFICATION_PENDING = 'LOGINPLAYER_VERIFICATION_PENDING';
export const LOGINPLAYER_VERIFICATION = 'LOGINPLAYER_VERIFICATION';