export const DEPOSIT_PLAYERINFORMATION_SUCCESS = 'DEPOSIT_PLAYERINFORMATION_SUCCESS';
export const DEPOSIT_PLAYERINFORMATION_ERROR  = 'DEPOSIT_PLAYERINFORMATION_ERROR';
export const DEPOSIT_PLAYERINFORMATION_PENDING = 'DEPOSIT_PLAYERINFORMATION_PENDING';
export const DEPOSIT_PLAYERINFORMATION = 'DEPOSIT_PLAYERINFORMATION';

export const DEPOSIT_APPROVE_PLAYERINFORMATION_SUCCESS = 'DEPOSIT_APPROVE_PLAYERINFORMATION_SUCCESS';
export const DEPOSIT_APPROVE_PLAYERINFORMATION_ERROR  = 'DEPOSIT_APPROVE_PLAYERINFORMATION_ERROR';
export const DEPOSIT_APPROVE_PLAYERINFORMATION_PENDING = 'DEPOSIT_APPROVE_PLAYERINFORMATION_PENDING';
export const DEPOSIT_APPROVE_PLAYERINFORMATION = 'DEPOSIT_APPROVE_PLAYERINFORMATION';

export const DEPOSIT_DECLINE_PLAYERINFORMATION_SUCCESS = 'DEPOSIT_DECLINE_PLAYERINFORMATION_SUCCESS';
export const DEPOSIT_DECLINE_PLAYERINFORMATION_ERROR  = 'DEPOSIT_DECLINE_PLAYERINFORMATION_ERROR';
export const DEPOSIT_DECLINE_PLAYERINFORMATION_PENDING = 'DEPOSIT_DECLNE_PLAYERINFORMATION_PENDING';
export const DEPOSIT_DECLINE_PLAYERINFORMATION = 'DEPOSIT_DECLINE_PLAYERINFORMATION';