export const TRANSACTIONHISTORY_SUCCESS = 'TRANSACTIONHISTORY_SUCCESS';
export const TRANSACTIONHISTORY_ERROR  = 'TRANSACTIONHISTORY_ERROR';
export const TRANSACTIONHISTORY_PENDING = 'TRANSACTIONHISTORY_PENDING';
export const TRANSACTIONHISTORY = 'TRANSACTIONHISTORY';